# Generated by Django 4.1.3 on 2022-11-07 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(choices=[('entrada principal', 'Entrada principal'), ('plato principal', 'Plato principal'), ('postre', 'Postre')], max_length=300)),
                ('vigencia', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vianda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal')], max_length=300)),
                ('tipoComida', models.CharField(choices=[('normal', 'Normal'), ('vegetariano', 'Vegetariano'), ('diabetico', 'Diabetico')], max_length=300)),
                ('fecha_inicio', models.DateField()),
                ('cantidad_vianda', models.IntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en preparacion', 'En preparación'), ('en camino', 'En camino'), ('entregado', 'Entregado'), ('devuelto', 'Devuelto'), ('cancelado', 'Cancelado')], max_length=350)),
                ('tipo_platos', models.ManyToManyField(to='vianda.tipo_plato')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
