# Generated by Django 4.1.3 on 2022-11-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vianda', '0002_alter_tipo_plato_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vianda',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en preparacion', 'En preparación'), ('en camino', 'En camino'), ('entregado', 'Entregado'), ('devuelto', 'Devuelto'), ('cancelado', 'Cancelado')], default='pendiente', max_length=350),
        ),
    ]
